Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [11]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
print(a1,'\n\n', a2, '\n\n', a3, '\n\n', a4, '\n\n', a5)


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [12]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(4, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 1)
print(a1,'\n\n', a2, '\n\n', a3, '\n\n', a4, '\n\n', a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


Ответ - Нельзя, т.к. по по сути этот массив содержит 12 массивов, состоящих из одного числа каждый.

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [16]:
a = np.random.normal(loc=0.0, scale=1.0, size=(3, 4))
print(a, '\n')
b = a.flatten()
print(b)

[[ 1.26111644 -0.20301621  1.11119838  0.00986064]
 [-0.07520026 -0.80524958 -0.69566859  0.33481676]
 [ 0.32000817  0.36266382 -1.25433792  2.17534542]] 

[ 1.26111644 -0.20301621  1.11119838  0.00986064 -0.07520026 -0.80524958
 -0.69566859  0.33481676  0.32000817  0.36266382 -1.25433792  2.17534542]


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [18]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [25]:
b = np.arange(20, 1, -2)
b.reshape(1, 10)
print(b)
#Разницы нет

[20 18 16 14 12 10  8  6  4  2]


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

In [32]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.vstack((a, b))
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [40]:
a = np.arange(1, 13)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
print(B)
d = np.linalg.det(B)
print(d)
B_inv = np.linalg.inv(B)
print(B_inv)
#Можно и получается вычислить обрантную матрицу для B - она квадратная, определитель отличен от нуля

[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
-1.3086255784530259e-25
[[-4.69124961e+13  7.03687442e+13  1.25000000e-01 -2.34562481e+13]
 [ 9.96890543e+13 -1.40737488e+14 -1.75921860e+13  5.86406201e+13]
 [-5.86406201e+13  7.03687442e+13  3.51843721e+13 -4.69124961e+13]
 [ 5.86406201e+12 -0.00000000e+00 -1.75921860e+13  1.17281240e+13]]


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [42]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно

In [44]:
c = np.random.randint(0, 16, (1, 16))
print(c)

[[ 3 12 14 10  7 12  4  6  9  2  6 10 10  7  4  3]]


Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [55]:
C = c.reshape(4, 4)
print('C = \n', C, '\n')

D = B + C * 10
print('D = \n', D, '\n')

det_D = np.linalg.det(D)
print('det(D) = ', det_D, '\n')

rang_D = np.linalg.matrix_rank(D)
print('rang D = ', rang_D, '\n')

D_inv = np.linalg.inv(D)
print('D_inv = \n', D_inv)

C = 
 [[ 3 12 14 10]
 [ 7 12  4  6]
 [ 9  2  6 10]
 [10  7  4  3]] 

D = 
 [[ 44 152 190 168]
 [102 197 162 227]
 [140 142 254 366]
 [168 237 306 395]] 

det(D) =  51290000.00000014 

rang D =  4 

D_inv = 
 [[-0.02210801 -0.024124   -0.03348801  0.05429596]
 [ 0.00291168  0.01346539 -0.00041529 -0.00859193]
 [ 0.00407643 -0.02258374 -0.01500487  0.02514798]
 [ 0.00449795  0.01967635  0.0261162  -0.03488789]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [60]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
print(D_inv, '\n')

E = np.where(D_inv == 1, B, C)
print(E)

[[0. 0. 0. 1.]
 [1. 1. 0. 0.]
 [1. 0. 0. 1.]
 [1. 1. 1. 0.]] 

[[  3  12  14  68]
 [ 32  77   4   6]
 [ 50   2   6 266]
 [ 68 167 266   3]]
